### ISSUE TITLE
Bug - Cards moved up or down one position using the shortcut return to their previous location once the page is refreshed

### ISSUE THREAD

**Issue by tosinalawale** [bulkan/shortcuts-for-trello#20] opened 2018-05-26 17:21 UTC
Cards moved up or down one position using the shortcut return to their previous location once the page is refreshed.

**Comment by tonytamps** [comment] 2018-05-28 23:00
Duplicate of #17 - the issue you commented in.

**Closed as completed by tonytamps** 2018-05-28 23:00 UTC
